name: hsp2_py38
channels:
  - conda-forge

dependencies:
  # Aligned with Anaconda 2021.05 (May 13, 2021)
  # package management
  - conda
  - conda-build
  - pip

  # Running HSP2
  - python =3.8*
  - scipy   # Scipy also installs numpy
  - pandas ==1.2.*  # Pandas installs most scientific Python modules, such as Numpy, etc.
  - numba ==0.53.1
  - numpy ==1.20.*  # for compatibility with numba version <0.53
  - hdf5 ==1.10.6    # latest compatible with both versions of PyTables & h5py below - doesn't work with setup.py
  - pytables ==3.6.1
  - h5py >=3.1
  - hdf5plugin  # HDF5 compression filters for h5py & jupyterlab_hdf
  - mando  # for Python CLI app in HSP2tools/HSP2_CLI.py; hasn't been updated since 2017 and doesn't support Python 3.9: https://github.com/rubik/mando

  # Interactivity & Visualization via Jupyter Notebooks (optional, but required for tutorials)
  - jupyterlab ==3.0.*  # also installs classic Jupyter notbook
  - ipympl  # jupyter-matplotlib, https://github.com/matplotlib/ipympl
  - nodejs    # required for many JupyterLab extensions
  - nb_conda  # Conda environment & package access extension from within Jupyter
  # HoloViz, https://holoviz.org
  - hvplot  # hvPlot installs most HoloViz libs, including matplotlib
  - ipywidgets  # Required for HoloViz interactivity in Jupyter notebooks

  # Dev tools (optional)
  - python-language-server
  - jupyter-lsp-python  # Includes both the server extension (jupyter-lsp) and pyls third-party server (python-language-server)
  - jupyterlab-lsp # Docs at https://github.com/krassowski/jupyterlab-lsp


  # PIP install requirements only if it is not possible with conda
  # https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html#using-pip-in-an-environment
  - pip:
    # Optional, but recommended for tutorials
    # - lckr-jupyterlab-variableinspector  # https://github.com/lckr/jupyterlab-variableInspector
    # - jupyterlab_hdf  # Explore HDF5 files in JupyterLab. Requires an additional step to install.
        # Installation instructions: https://github.com/jupyterlab/jupyterlab-hdf5#installation
